spring:
  profiles:
    active: default

schedule:
  database:
    url: jdbc:mysql://localhost:3306/schedule?autoReconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: otis.missouri
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1

---
spring:
  profiles: mac

schedule:
  database:
    url: jdbc:mysql://localhost:3306/schedule?autoReconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: otis.missouri
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1