spring:
  profiles:
    active: default

sql:
  user:
    insertUserSql: insert into users (student_id, first_name, last_name) values (:student_id,:first_name,:last_name)
    getUserByIdSql: select * from users where student_id = :student_id
    deleteUserByIdSql: delete from users where student_id = :student_id
    updateUserByIdSql: update users set first_name = :first_name, last_name = :last_name where student_id = :student_id

  course:
    getAllCoursesSql: SELECT * from course
    insertCourseSql: insert into course (department, course_number, credits, description, learning_objective, prereqs, coreqs) values (:description, :course_number, :credits, :description, :learning_objective, :prereqs, :coreqs)
    getCourseByNumber: select * from course where course_number =:course_number
    deleteCourseByNumber: delete from course where course_number
    updateCourseByNumber : update course set department = :department, credits = :credits, description =:description, learning_objectives = :learning_objectives, prereqs = :prereqs, coreqs = :coreqs
schedule:
  database:
    url: jdbc:mysql://localhost:3306/schedule
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1

---
spring:
  profiles: mac

schedule:
  database:
    url: jdbc:mysql://localhost:3306/schedule?autoReconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: otis.missouri
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1